import React from "react";

export default function Grid() {
  return (
    <div className="opacity-[0.04] fixed bottom-0 left-0 grid w-full h-full min-h-screen grid-cols-[repeat(18,1fr)] gap-[1px] bg-spotify-green min-w-screen -z-30 ">
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />{" "}
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
      <div className="col-span-1 row-span-1 rounded-lg min-w-[95px] bg-spotify-bg" />
    </div>
  );
}
